#!/bin/sh

if [ -z $1 ];then
echo "Please specify the repository name as the first switch to this script"
exit
fi

if [ -z $2 ];then
echo "Please specify user@host.tld as the second switch to this script"
exit
fi

ssh $2 'mkdir -p ~/git/'$1'.git && cd ~/git/'$1'.git && git --bare init'
mkdir $1
cd $1
git init
git remote add $1 ssh://$2/~/git/$1.git
touch .gitignore
git add .
git commit -m 'Created new repo'
git push $1 master
echo "
[branch \"master\"]
remote = $1
merge = refs/heads/master" >>.git/config
echo "Your new git repo '$1' is ready and initialized at $2/~/git/$1.git" 